# Generated by Django 5.0.3 on 2024-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolcourse',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
